-- ============================================================
-- Kalaharian Trading Bot: Signals & Settings Infrastructure
-- Tables: trading_signals, bot_settings
-- Auth: supabase_auth with auth.uid() RLS
-- ============================================================

-- 1. TRADING SIGNALS TABLE
-- Stores CRT/SMC signals generated by the Kalaharian bot per user
CREATE TABLE IF NOT EXISTS public.trading_signals (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  asset_symbol TEXT NOT NULL,
  signal_type TEXT NOT NULL CHECK (signal_type IN ('BOS', 'CHOCH', 'CRT_SWEEP', 'ORDER_BLOCK', 'FVG', 'AMD', 'LIQUIDITY_GRAB')),
  direction TEXT NOT NULL CHECK (direction IN ('BULLISH', 'BEARISH', 'NEUTRAL')),
  message_en TEXT NOT NULL DEFAULT '',
  message_tn TEXT NOT NULL DEFAULT '',
  message_kg TEXT NOT NULL DEFAULT '',
  price_at_signal NUMERIC(20, 8),
  confidence NUMERIC(5, 2) DEFAULT 0 CHECK (confidence >= 0 AND confidence <= 100),
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for trading_signals
CREATE INDEX IF NOT EXISTS idx_trading_signals_user_id ON public.trading_signals(user_id);
CREATE INDEX IF NOT EXISTS idx_trading_signals_asset_symbol ON public.trading_signals(asset_symbol);
CREATE INDEX IF NOT EXISTS idx_trading_signals_created_at ON public.trading_signals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trading_signals_signal_type ON public.trading_signals(signal_type);

-- Enable RLS
ALTER TABLE public.trading_signals ENABLE ROW LEVEL SECURITY;

-- RLS Policies for trading_signals
-- Users can only SELECT their own signals
CREATE POLICY "Users can view own signals"
  ON public.trading_signals
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Users can INSERT their own signals
CREATE POLICY "Users can insert own signals"
  ON public.trading_signals
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Users can UPDATE their own signals
CREATE POLICY "Users can update own signals"
  ON public.trading_signals
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Users can DELETE their own signals
CREATE POLICY "Users can delete own signals"
  ON public.trading_signals
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);


-- 2. BOT SETTINGS TABLE
-- Stores per-user Kalaharian bot configuration
CREATE TABLE IF NOT EXISTS public.bot_settings (
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  language TEXT NOT NULL DEFAULT 'en' CHECK (language IN ('en', 'tn', 'kg')),
  enabled_strategies TEXT[] DEFAULT ARRAY['BOS', 'CHOCH', 'CRT_SWEEP']::TEXT[],
  risk_level TEXT NOT NULL DEFAULT 'medium' CHECK (risk_level IN ('low', 'medium', 'high')),
  take_profit NUMERIC(5, 2) DEFAULT 2.00,
  stop_loss NUMERIC(5, 2) DEFAULT 1.00,
  bot_enabled BOOLEAN DEFAULT false,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.bot_settings ENABLE ROW LEVEL SECURITY;

-- RLS Policies for bot_settings
-- Users can only SELECT their own settings
CREATE POLICY "Users can view own settings"
  ON public.bot_settings
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Users can INSERT their own settings
CREATE POLICY "Users can insert own settings"
  ON public.bot_settings
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- Users can UPDATE their own settings
CREATE POLICY "Users can update own settings"
  ON public.bot_settings
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Users can DELETE their own settings
CREATE POLICY "Users can delete own settings"
  ON public.bot_settings
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);


-- 3. AUTO-UPDATE updated_at TRIGGER for bot_settings
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_bot_settings_updated_at ON public.bot_settings;
CREATE TRIGGER trigger_bot_settings_updated_at
  BEFORE UPDATE ON public.bot_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();
